AllCops:
  DisplayCopNames: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ModuleFunction:
  Enabled: false

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 8
